'use client'

import '@/services/scss/globals.scss'
import { Manrope } from 'next/font/google'
import { Providers } from './provider';
import Header from '@/components/layouts/header';
import { M_AROGGA } from '@/utils/static-urls';

const font = Manrope({
  subsets: ['latin'],
  display: 'swap',
});

// export const metadata = {
//   title: 'Arogga',
//   description: 'Generated by create next app',
//   alternates: {
//     canonical: M_AROGGA,
//   },

// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <title>Test</title>
      <body className={font.className}>
        <Providers>
          <Header />
          <main>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
